# Лекция. Типы, структуры и форматы данных

In [1]:
import pandas as pd

## § 1. Типы данных

Прежде чем переходить к структурам данных для Data Science, напомним основные типы данных: 
- целые числа, 
- числа с плавающей запятой, 
- строки,
- логические значения.

In [4]:
name = 'Катя Иванова'
age = 19
average_score = 3.2
A_student = average_score == 5
A_student

False

In [5]:
type(name), type(age), type(average_score), type(A_student)

(str, int, float, bool)

Есть и другие типы (например, даты, комплексные числа и т. д.), а хуже всего то, что в Питоне часто бывает невозможно отличить тип данных от структуры данных (например, список — это одновременно и тип, и структура). Но мы не будем зацикливаться на этой терминологической казуистике, и другие типы указывать тоже не будем. Для наших задач нам вполне хватит того, что мы перечислили выше.

### Pandas и формат csv

Прочитаем файл о продажах гаджетов:

In [6]:
df = pd.read_csv('data/gadget_sales.csv')
df

,order_id,customer_id,product,price,rating,quantity,order_date,phone_number,in_stock
0,ORD001,101,Smartphone,999.99,Top,1,2024-01-15,79161234567,Yes
1,ORD002,102,Laptop,1499.99,Medium,1,2024-01-16,79161234568,No
2,ORD003,103,Tablet,499.99,Medium,2,2024-01-17,79161234569,Yes
3,ORD004,104,Smartphone,999.99,Top,1,2024-01-18,79161234570,Yes
4,ORD005,105,Headphones,199.99,Low,3,2024-01-19,79161234571,Yes
5,ORD006,106,Laptop,"1499,99",Medium,1,2024-01-20,79161234572,No
6,ORD007,107,Tablet,499.99,Medium,2,2024-01-21,79161234573,Yes
7,ORD008,108,Smartwatch,299.99,Low,1,2024-01-22,79161234574,Yes
8,ORD009,109,Headphones,199.99,Low,2,2024-01-23,79161234575,Yes
9,ORD010,110,Smartphone,999.99,Top,1,2024-01-24,79161234576,Yes

Вот его описание:

- order_id — ID заказа,
- customer_id — ID покупателя,
- product — товар,
- price — цена в долларах США,
- quantity — количество купленных единиц товара в одном заказе
- order_date — дата заказа,
- phone_number — телефон покупателя,
- rating — рейтинг товара,
- in_stock — есть ли в наличии.

>#### Задание
Перейдите в папку data и посмотрите на файл gadget_sales.csv «изнутри».
А теперь «снаружи»: выведите информацию о данных при помощи метода `info`. Что не так?

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      10 non-null     object
 1   customer_id   10 non-null     int64
 2   product       10 non-null     object
 3   price         10 non-null     object
 4   rating        10 non-null     object
 5   quantity      10 non-null     int64
 6   order_date    10 non-null     object
 7   phone_number  10 non-null     int64
 8   in_stock      10 non-null     object
dtypes: int64(3), object(6)
memory usage: 852.0+ bytes

Почему так происходит? — потому что Pandas сначала удаляет кавычки (это часть парсинга CSV), потом анализирует  значения, и если значение выглядит как число, преобразует его в число (а если как строка, то в строку). Кавычки в CSV — это просто способ экранировать данные (например, если есть запятые внутри значения). Они не влияют на определение типа. Единственный способ заставить pandas читать данные так как вам надо — явно указать `dtype` при чтении.

In [8]:
df = pd.read_csv('data/gadget_sales.csv', dtype={'customer_id': str})
display(df)
df.info()

,order_id,customer_id,product,price,rating,quantity,order_date,phone_number,in_stock
0,ORD001,0101,Smartphone,999.99,Top,1,2024-01-15,79161234567,Yes
1,ORD002,0102,Laptop,1499.99,Medium,1,2024-01-16,79161234568,No
2,ORD003,0103,Tablet,499.99,Medium,2,2024-01-17,79161234569,Yes
3,ORD004,0104,Smartphone,999.99,Top,1,2024-01-18,79161234570,Yes
4,ORD005,0105,Headphones,199.99,Low,3,2024-01-19,79161234571,Yes
5,ORD006,0106,Laptop,"1499,99",Medium,1,2024-01-20,79161234572,No
6,ORD007,0107,Tablet,499.99,Medium,2,2024-01-21,79161234573,Yes
7,ORD008,0108,Smartwatch,299.99,Low,1,2024-01-22,79161234574,Yes
8,ORD009,0109,Headphones,199.99,Low,2,2024-01-23,79161234575,Yes
9,ORD010,0110,Smartphone,999.99,Top,1,2024-01-24,79161234576,Yes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      10 non-null     object
 1   customer_id   10 non-null     object
 2   product       10 non-null     object
 3   price         10 non-null     object
 4   rating        10 non-null     object
 5   quantity      10 non-null     int64
 6   order_date    10 non-null     object
 7   phone_number  10 non-null     int64
 8   in_stock      10 non-null     object
dtypes: int64(2), object(7)
memory usage: 852.0+ bytes

Теперь ID покупателя — это строка.

После прочтения можно изменить тип данных в каком-либо столбце при помощи метода `astype`. Например, телефон — это тоже не число, а строка, а цена — наоборот: не строка, а число с плавающей запятой. 

С телефонным номером разобраться нетрудно:

In [9]:
df['phone_number'] = df['phone_number'].astype(str)
display(df)
df.info()

,order_id,customer_id,product,price,rating,quantity,order_date,phone_number,in_stock
0,ORD001,0101,Smartphone,999.99,Top,1,2024-01-15,79161234567,Yes
1,ORD002,0102,Laptop,1499.99,Medium,1,2024-01-16,79161234568,No
2,ORD003,0103,Tablet,499.99,Medium,2,2024-01-17,79161234569,Yes
3,ORD004,0104,Smartphone,999.99,Top,1,2024-01-18,79161234570,Yes
4,ORD005,0105,Headphones,199.99,Low,3,2024-01-19,79161234571,Yes
5,ORD006,0106,Laptop,"1499,99",Medium,1,2024-01-20,79161234572,No
6,ORD007,0107,Tablet,499.99,Medium,2,2024-01-21,79161234573,Yes
7,ORD008,0108,Smartwatch,299.99,Low,1,2024-01-22,79161234574,Yes
8,ORD009,0109,Headphones,199.99,Low,2,2024-01-23,79161234575,Yes
9,ORD010,0110,Smartphone,999.99,Top,1,2024-01-24,79161234576,Yes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      10 non-null     object
 1   customer_id   10 non-null     object
 2   product       10 non-null     object
 3   price         10 non-null     object
 4   rating        10 non-null     object
 5   quantity      10 non-null     int64
 6   order_date    10 non-null     object
 7   phone_number  10 non-null     object
 8   in_stock      10 non-null     object
dtypes: int64(1), object(8)
memory usage: 852.0+ bytes

>#### Задание
Почему код страны идет без плюса? Ведь в самом csv Россия отмечена как +7? Как это исправить?

In [10]:
df = pd.read_csv('data/gadget_sales.csv', dtype={'customer_id': str, 'phone_number': str})
display(df)
df.info()

,order_id,customer_id,product,price,rating,quantity,order_date,phone_number,in_stock
0,ORD001,0101,Smartphone,999.99,Top,1,2024-01-15,+79161234567,Yes
1,ORD002,0102,Laptop,1499.99,Medium,1,2024-01-16,+79161234568,No
2,ORD003,0103,Tablet,499.99,Medium,2,2024-01-17,+79161234569,Yes
3,ORD004,0104,Smartphone,999.99,Top,1,2024-01-18,+79161234570,Yes
4,ORD005,0105,Headphones,199.99,Low,3,2024-01-19,+79161234571,Yes
5,ORD006,0106,Laptop,"1499,99",Medium,1,2024-01-20,+79161234572,No
6,ORD007,0107,Tablet,499.99,Medium,2,2024-01-21,+79161234573,Yes
7,ORD008,0108,Smartwatch,299.99,Low,1,2024-01-22,+79161234574,Yes
8,ORD009,0109,Headphones,199.99,Low,2,2024-01-23,+79161234575,Yes
9,ORD010,0110,Smartphone,999.99,Top,1,2024-01-24,+79161234576,Yes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      10 non-null     object
 1   customer_id   10 non-null     object
 2   product       10 non-null     object
 3   price         10 non-null     object
 4   rating        10 non-null     object
 5   quantity      10 non-null     int64
 6   order_date    10 non-null     object
 7   phone_number  10 non-null     object
 8   in_stock      10 non-null     object
dtypes: int64(1), object(8)
memory usage: 852.0+ bytes

С ценой чуть сложнее. Ести мы сразу попытаемся применить уже знакомый нам метод `astype` (и даже если мы попытаемся при чтении указать тип `float`), то ничего не получится, так как код не справится с запятой в качестве десятичного разделителя.

Поэтому сначала воспользуемся методом `replace` и заменим  запятую на точку в каждой нужной позиции датафрейма:

In [11]:
price_new = []

for x in df['price']:
    price_new.append(x.replace(',', '.'))

df['price'] = price_new
display(df)
df.info()

,order_id,customer_id,product,price,rating,quantity,order_date,phone_number,in_stock
0,ORD001,0101,Smartphone,999.99,Top,1,2024-01-15,+79161234567,Yes
1,ORD002,0102,Laptop,1499.99,Medium,1,2024-01-16,+79161234568,No
2,ORD003,0103,Tablet,499.99,Medium,2,2024-01-17,+79161234569,Yes
3,ORD004,0104,Smartphone,999.99,Top,1,2024-01-18,+79161234570,Yes
4,ORD005,0105,Headphones,199.99,Low,3,2024-01-19,+79161234571,Yes
5,ORD006,0106,Laptop,1499.99,Medium,1,2024-01-20,+79161234572,No
6,ORD007,0107,Tablet,499.99,Medium,2,2024-01-21,+79161234573,Yes
7,ORD008,0108,Smartwatch,299.99,Low,1,2024-01-22,+79161234574,Yes
8,ORD009,0109,Headphones,199.99,Low,2,2024-01-23,+79161234575,Yes
9,ORD010,0110,Smartphone,999.99,Top,1,2024-01-24,+79161234576,Yes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      10 non-null     object
 1   customer_id   10 non-null     object
 2   product       10 non-null     object
 3   price         10 non-null     object
 4   rating        10 non-null     object
 5   quantity      10 non-null     int64
 6   order_date    10 non-null     object
 7   phone_number  10 non-null     object
 8   in_stock      10 non-null     object
dtypes: int64(1), object(8)
memory usage: 852.0+ bytes

И только теперь можно именить тип данных в столбце price:

In [12]:
df['price'] = df['price'].astype(float)
display(df)
df.info()

,order_id,customer_id,product,price,rating,quantity,order_date,phone_number,in_stock
0,ORD001,0101,Smartphone,999.99,Top,1,2024-01-15,+79161234567,Yes
1,ORD002,0102,Laptop,1499.99,Medium,1,2024-01-16,+79161234568,No
2,ORD003,0103,Tablet,499.99,Medium,2,2024-01-17,+79161234569,Yes
3,ORD004,0104,Smartphone,999.99,Top,1,2024-01-18,+79161234570,Yes
4,ORD005,0105,Headphones,199.99,Low,3,2024-01-19,+79161234571,Yes
5,ORD006,0106,Laptop,1499.99,Medium,1,2024-01-20,+79161234572,No
6,ORD007,0107,Tablet,499.99,Medium,2,2024-01-21,+79161234573,Yes
7,ORD008,0108,Smartwatch,299.99,Low,1,2024-01-22,+79161234574,Yes
8,ORD009,0109,Headphones,199.99,Low,2,2024-01-23,+79161234575,Yes
9,ORD010,0110,Smartphone,999.99,Top,1,2024-01-24,+79161234576,Yes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      10 non-null     object
 1   customer_id   10 non-null     object
 2   product       10 non-null     object
 3   price         10 non-null     float64
 4   rating        10 non-null     object
 5   quantity      10 non-null     int64
 6   order_date    10 non-null     object
 7   phone_number  10 non-null     object
 8   in_stock      10 non-null     object
dtypes: float64(1), int64(1), object(7)
memory usage: 852.0+ bytes

>#### Задание
>1. Поменяйте тип столбца `in_stock` на логический.
>2. Сохраните датафрейм в файл csv под новым именем и снова откройте его. Что поменялось? Все ли в порядке при чтении файла? Что нужно сделать, чтобы столбцы относились к нужным типам?

In [ ]:
# Код

## § 2. Структуры данных

Структуры данных в Python — это способы организации данных в памяти, которые позволяют управлять информацией: добавлять, удалять, искать или изменять элементы. Они играют важную роль в анализе данных, так как помогают оптимизировать работу кода, повысить его быстродействие и снизить расход памяти.

### Некоторые встроенные структуры данных в Python

**Списки (list)** —  упорядоченная изменяемая коллекция элементов, которые могут быть разных типов. Элементы хранятся в памяти последовательно, к ним можно обращаться по индексу. Списки динамические — их размер может меняться. 

**Кортежи (tuple)** —  упорядоченная неизменяемая коллекция элементов. После создания нельзя добавить, удалить или изменить элементы кортежа. Могут содержать разные типы данных: целые числа, строки, списки и т. д.

**Словари (dict)** —  неупорядоченная (до Python 3.7) или упорядоченная (с Python 3.7) изменяемая коллекция пар «ключ — значение». Ключи должны быть уникальными и неизменяемыми (например, строки, числа, кортежи), а значения могут быть любого типа. Начиная с Python 3.7, словари сохраняют порядок добавления элементов. 

**Множества (set)** —  неупорядоченная коллекция уникальных элементов. Дубликаты автоматически удаляются. Элементы множества должны быть неизменяемыми. Оптимизированы для быстрой проверки вхождения элементов, а также для операций объединения, пересечения и разности.

### Не встроенные, но основные структуры данных для Data Science

**Массивы (np.array)** — структура данных, которая поддерживает произвольное число измерений, векторизованные операции и богатый набор математических функций. 

**Серии (pd.Series)** — одномерная структура данных, представляющая собой помеченный массив. Она может хранить данные любого типа: числа, строки, объекты Python и другие типы. 

**Датафреймы (pd.DataFrame)** — двумерная структура данных, которая представляет собой таблицу со строками и столбцами, организованными в виде двумерного массива.

## § 3. Списки

Списки (lists) — это одна из самых важных и часто используемых структур данных в Python.

In [24]:
names = ['Катя', 'Петя', 'Леша', 'Аня']
numbers = [1, 3, 3.14, round(2**0.5, 2)]
mixed = ['Катя', 3.14, True]
numbers

[1, 3, 3.14, 1.41]

Обратите внимание, что, если применить к списку функцию `type`, то Python идентифицирует результат, относящийся к типу `list`, хотя на самом деле `list` — это не тип данных, а структура, которая может содержать объекты разных типов.

In [14]:
type(names)

list

Основные характеристики списков таковы:
- они индексируемы — элементы списка можно перечислять по порядку,
- изменяемы — можно изменять элементы списков, а также добавлять и удалять элементы,
- могут содержать элементы разных типов,
- поддерживают срезы.

### Индексация списков
Индексация списков начинается с 0. То есть, первый элемент имеет индекс 0, второй — индекс 1 и так далее. Последний элемент имеет индекс, равный длине списка плюс 1 (это не очень удобно, но к этому можно привыкнуть). Зато последний элемент имеет также индекс –1, предпоследний — индекс –2 и так далее (а это очень удобно, и привычка к этому возникает очень быстро). 

Доступ к элементам списка осуществляется по индексу. Например:

In [15]:
print('Первое имя:', names[0])
print('Последнее имя:', names[-1])
print('Предпоследнее имя:', names[-2])

Первое имя: Катя
Последнее имя: Аня
Предпоследнее имя: Леша

Для вычисления длины списка используется встроенная функция `len`:

In [16]:
len(names)

4

### Изменение списков
Изменение списков в Python — это операции, позволяющие модифицировать содержимое списка после его создания: можно добавлять, удалять и заменять элементы. Например, заменим первое имя в списке на Виолетту:

In [25]:
names[0] = 'Виолетта'
names

['Виолетта', 'Петя', 'Леша', 'Аня']

Добавим в конец списка еще одно имя. Пусть это будет Ваня:

In [26]:
names.append('Ваня')
names

['Виолетта', 'Петя', 'Леша', 'Аня', 'Ваня']

Вставим между Виолеттой и Петей, (то есть, на первое место) имя Слава:

In [27]:
names.insert(1, 'Слава')
names

['Виолетта', 'Слава', 'Петя', 'Леша', 'Аня', 'Ваня']

Обратите внимание, что весь «хвост» списка сохранился, но сдвинулся направо (при этом длина списка, естественно увеличилась на одну позицию).

### Срезы списков
Еще одна важная операция, которую часто приходится выполнять со списками — это срезы. Срезы списков в Python — это механизм, который позволяет извлекать подмножество элементов из списка, создавая новый список с выбранными элементами, при этом исходный список остаётся неизменным. Срезы упрощают работу с данными, позволяя быстро получать нужные фрагменты без использования циклов и дополнительных условий.

Базовый синтаксис среза выглядит так:
```pithon
list_name[begin:end:step]
```
Где `begin` — индекс первого элемента, который будет включён в срез (отсчёт начинается с 0);
`end` — индекс элемента, перед которым срез завершится (этот элемент не включается в срез);
`step` — интервал между выбираемыми элементами (по умолчанию равен 1).

Например, в списке имен все элементы списка с начала до третьего элемента, исключая третий элемент (то есть, по сути, все элементы вплоть до второго включительно) получаются как такой срез:

In [28]:
names[:3]

['Виолетта', 'Слава', 'Петя']

Напомним, что индекс Пети — это 2, то есть, третьего элемента в списке действительно нет. В обратную сторону, все элементы списка имен, начиная с третьего и до конца, получаются так:

In [29]:
names[3:]

['Леша', 'Аня', 'Ваня']

Элементы с первого по четвертый (включая первый, но исключая четвертый) получаются так:

In [32]:
names[1:4]

['Слава', 'Петя', 'Леша']

Это основные срезы, которые используются чаще всего. Вообще, со срезами можно вытворять удивительные штуки, которые далеко не всегда являются очевидными (например, если параметры среза отрицательны, то отсчёт фактически будет вестись справа налево, и что при этом получится — заранее сказать очень трудно). Но нам вполне хватит этих трёх типов срезов, и углубляться в эту тему мы не станем.

### Копии списков

Очень важно правильно создавать копии списков, потому что, если делать это небрежно, то можно получить неожиданные результаты, которые противоречат здравому смыслу. Например, возьмём список имен `names` и создадим новый список имен `names_new`, просто присвоив переменной соответствующее значение:

In [33]:
names_new = names
names_new

['Виолетта', 'Слава', 'Петя', 'Леша', 'Аня', 'Ваня']

Теперь добавим имя Джо в конец нового списка:

In [34]:
names_new.append('Джо')
names_new

['Виолетта', 'Слава', 'Петя', 'Леша', 'Аня', 'Ваня', 'Джо']

А теперь выведем старый список имен:

In [35]:
names

['Виолетта', 'Слава', 'Петя', 'Леша', 'Аня', 'Ваня', 'Джо']

И вот оно, дикое противоречие. Мы же работали с новым объектом (это нам так кажется, на самом деле, мы работали со старым объектом), почему вместе с ним преобразовался старый? Ответ — потому что, выполнив присваивание, мы не создали новый объект: мы создали новую ссылку на старый объект.

За этим нужно следить и не допускать таких ошибок. Правильное решение — использовать метод `copy` (при этом действительно создаётся новый объект). То есть, если мы выполним сначала копирование, а потом добавление, то старый объект не изменится:

In [36]:
names_new_new = names.copy()

names_new_new.append('Дональд')
names_new_new

['Виолетта', 'Слава', 'Петя', 'Леша', 'Аня', 'Ваня', 'Джо', 'Дональд']

In [37]:
names

['Виолетта', 'Слава', 'Петя', 'Леша', 'Аня', 'Ваня', 'Джо']

Теперь Дональд появился в новом списке, но не появился в старом. Правда, в старом остался Джо, которого мы не собирались туда вносить, и теперь его нужно оттуда вычистить, приложив для этого специальные усилия:

In [38]:
names.remove('Джо')
names

['Виолетта', 'Слава', 'Петя', 'Леша', 'Аня', 'Ваня']

### Вложенные списки
Вложенные списки — это списки, элементами которых служат списки. Причем, вложенные списки могут иметь разную длину и относится к разным типам. Например:

In [39]:
double_list = [names, numbers]
double_list

[['Виолетта', 'Слава', 'Петя', 'Леша', 'Аня', 'Ваня'], [1, 3, 3.14, 1.41]]

С точки зрения математики, это полная и окончательная жуть. И это ещё не все. Списки внутри списков сами по себе могут быть вложенными, обладать различными длинами и уровнями вложенности и так далее. Это ещё большая жуть (для математиков, а вот для программистов это как раз нормально). Мы не будем этого делать. Мы будем воспринимать вложенные списки как матрицы, то есть, ограничимся ситуацией, когда:
- уровней вложенности — один,
- длины вложенных списков — равны между собой.

In [40]:
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Отображение у вложенных списков, конечно, так себе. На матрицу не похоже (забегая веред, отметим, что это будет исправлено, когда от списков мы перейдем к массивам `np.array`).

### Генераторы списков

Генераторы списков в Python — это компактный способ создания новых списков на основе существующих итерируемых объектов (списков, строк, диапазонов чисел и т. д.). Они позволяют заменить многострочные циклы `for` одной лаконичной строкой кода.

Базовый синтаксис генератора списка:

```python
[expression for element in array_like if condition]
```
Где `expression` — действие, которое выполняется над каждым элементом; `element` — переменная, принимающая значения из итерируемого объекта; `array_like` — объект, по которому можно проходить в цикле (список, строка, range, одномерный массив, столбец датафрейма и т. п.); `condition` (опционально) — фильтр, оставляющий только элементы, удовлетворяющие заданному критерию.

Вот, например, список квадратов всех целых чисел от 0 до 9 включительно при условии, что эти числа не кратны 3:

In [41]:
[x**2 for x in range(10) if x % 3 != 0]

[1, 4, 16, 25, 49, 64]

А вот аналог этого кода, исполненный при помощи классических операторов `for` и `if`:

In [42]:
s = []
for x in range(10):
    if x % 3 != 0:
        s.append(x**2)
        
s

[1, 4, 16, 25, 49, 64]

Генераторы списков обладают целым рядом преимуществ:
- Краткость — сокращают код с нескольких строк до одной.
- Производительность — работают на 20–30 % быстрее обычных циклов.
- Читаемость — чётко описывают намерение («создать список, где каждый элемент — это X для Y из Z»).
- Локализация переменных — переменные внутри генератора не «утекают» в глобальную область видимости.

Действие, которое исполняется в генераторе, не обязательно должно быть математическим. Например, так можно получить список с длинами имён из списка имён, который мы использовали выше:

In [43]:
[len(name) for name in names]

[8, 5, 4, 4, 3, 4]

Для того, чтобы исполнить полный перебор вариантов, нужно изменить синтаксис:
```python
[expression_1 if condition else expression_2  for element in array_like ]
```
Например, чтобы все некратные тройке числа заменить на их квадраты, а все кратные оставить как есть, выполняется следующий код:

In [44]:
[x**2 if x % 3 != 0 else x for x in range(10)]

[0, 1, 4, 3, 16, 25, 6, 49, 64, 9]

В общем, это отличный способ получения новых списков на основе старых. И, кстати, исходный итерируемый объект при этом не изменяется, так что можно не опасаться неожиданных сюрпризов. Однако, не стоит злоупотреблять сложностью: для логически запутанной генерации лучше использовать обычные циклы — это повысит читаемость кода и понизит вероятность ошибки.

>#### Задание
Вернемся к продаже гаджетов и допустим, что теперь планшеты будут продаваться со скидкой 15%. При помощи генератора списков добавьте в датафрейм колонку `discount`, которая отобразит эти сведения.

In [45]:
df['discount'] = [0.15 if x == 'Tablet' else 0 for x in df['product']]
df

,order_id,customer_id,product,price,rating,quantity,order_date,phone_number,in_stock,discount
0,ORD001,0101,Smartphone,999.99,Top,1,2024-01-15,+79161234567,Yes,0.00
1,ORD002,0102,Laptop,1499.99,Medium,1,2024-01-16,+79161234568,No,0.00
2,ORD003,0103,Tablet,499.99,Medium,2,2024-01-17,+79161234569,Yes,0.15
3,ORD004,0104,Smartphone,999.99,Top,1,2024-01-18,+79161234570,Yes,0.00
4,ORD005,0105,Headphones,199.99,Low,3,2024-01-19,+79161234571,Yes,0.00
5,ORD006,0106,Laptop,1499.99,Medium,1,2024-01-20,+79161234572,No,0.00
6,ORD007,0107,Tablet,499.99,Medium,2,2024-01-21,+79161234573,Yes,0.15
7,ORD008,0108,Smartwatch,299.99,Low,1,2024-01-22,+79161234574,Yes,0.00
8,ORD009,0109,Headphones,199.99,Low,2,2024-01-23,+79161234575,Yes,0.00
9,ORD010,0110,Smartphone,999.99,Top,1,2024-01-24,+79161234576,Yes,0.00

## § 4. Кортежи

Кортеж в Python — это упорядоченная, неизменяемая коллекция элементов, которые могут быть разных типов. Проще говоря, это список, который нельзя изменить после создания. 

Элементами кортежа могут быть объекты разных типов данных: числа, строки, списки, другие кортежи и другие. Кортежи могут иметь неограниченную глубину вложенности: например, кортеж может включать в себя список, который будет содержать другой список, который вновь будет содержать кортеж и так далее.

Кортеж создается при помощи круглых скобок:

In [46]:
subjects = ('Линейная алгебра', 'Математический анализ', 'Теория вероятностей', 'Анализ данных', 'Python', 'SQL')
subjects

('Линейная алгебра',
 'Математический анализ',
 'Теория вероятностей',
 'Анализ данных',
 'Python',
 'SQL')

Или без скобок, просто через запятую (но лучше со скобками):

In [47]:
sections = 'Основы линейной алгебры', 'Векторные пространства', 'Линейные операторы', 'Квадратичные формы'
sections

('Основы линейной алгебры',
 'Векторные пространства',
 'Линейные операторы',
 'Квадратичные формы')

### Связь списков и кортежей

Если есть какой-нибудь список, его можно преобразовать в кортеж при помщи функции `tuple`. Например, наш список имён, который мы использовали выше:

In [48]:
names_tuple = tuple(names)
names_tuple

('Виолетта', 'Слава', 'Петя', 'Леша', 'Аня', 'Ваня')

Теперь мы имеем кортеж, и если мы захотим с ним что-нибудь сделать (изменить, добавить или удалить какой-нибудь элемент), у нас ничего не получиться.

In [51]:
# names_tuple[0] = 'Оля'
# names_tuple.append('Джо')

И наоборот: если есть какой-нибудь кортеж, его можно преобразовать в список:

In [52]:
names_list = list(names_tuple)
names_list

['Виолетта', 'Слава', 'Петя', 'Леша', 'Аня', 'Ваня']

### Действия с кортежами

С кортежами (в отличие от списков) вообще мало что можно сделать. Можно обратиться по индексу:

In [53]:
names_tuple[0]

'Виолетта'

In [54]:
names_tuple[0], names_tuple[1]

('Виолетта', 'Слава')

Кстати, обратите внимание: вывод данной ячейки представляет собой не что иное как кортеж, потому что два вывода были указаны через запятую (причем, это характерно не только для работы с кортежами, а вообще для любых выводов, перечисленных через запятую).

Можно взять срез кортежа:

In [55]:
names_tuple[2:4]

('Петя', 'Леша')

Результатом снова будет кортеж. Можно вычислить длину кортежа:

In [56]:
len(names_tuple)

6

А больше, пожалуй, ничего сделать нельзя. И вообще — коротежи весьма редко используются в Data Science. Нужно просто знать, что такая структура есть. Кортежи используют, когда нужно защитить данные от случайного изменения — например:
- для представления фиксированных структур данных — координат или настроек конфигурации,
- для возврата нескольких значений из функции — это упрощает структуру кода и делает его более читаемым,
- в качестве ключей словарей — кортежи могут использоваться в качестве ключей, в отличие от списков.

>#### Задание
На самом деле, телефонный номер — это даже не строка, а кортеж из трех строк, где первый элемент кодирует страну, второй элемент (а точнее, комбинация первого и второго) — оператора, а третий элемент — конкретного абонента. Запишите телефонные номера в виде кортежей.

In [57]:
df['phone_number'] = [(x[:2], x[2:5], x[5:]) for x in df['phone_number']]
df

,order_id,customer_id,product,price,rating,quantity,order_date,phone_number,in_stock,discount
0,ORD001,0101,Smartphone,999.99,Top,1,2024-01-15,"(+7, 916, 1234567)",Yes,0.00
1,ORD002,0102,Laptop,1499.99,Medium,1,2024-01-16,"(+7, 916, 1234568)",No,0.00
2,ORD003,0103,Tablet,499.99,Medium,2,2024-01-17,"(+7, 916, 1234569)",Yes,0.15
3,ORD004,0104,Smartphone,999.99,Top,1,2024-01-18,"(+7, 916, 1234570)",Yes,0.00
4,ORD005,0105,Headphones,199.99,Low,3,2024-01-19,"(+7, 916, 1234571)",Yes,0.00
5,ORD006,0106,Laptop,1499.99,Medium,1,2024-01-20,"(+7, 916, 1234572)",No,0.00
6,ORD007,0107,Tablet,499.99,Medium,2,2024-01-21,"(+7, 916, 1234573)",Yes,0.15
7,ORD008,0108,Smartwatch,299.99,Low,1,2024-01-22,"(+7, 916, 1234574)",Yes,0.00
8,ORD009,0109,Headphones,199.99,Low,2,2024-01-23,"(+7, 916, 1234575)",Yes,0.00
9,ORD010,0110,Smartphone,999.99,Top,1,2024-01-24,"(+7, 916, 1234576)",Yes,0.00

## § 5. Словари

Словарь в Python — это структура данных, которая хранит информацию в виде пар «ключ: значение» («key»-«value»). 

Это аналог бумажных словарей или записных книжек, где каждому ключу соответствует определённое значение. Считается, что связь между словарем в Python и  словарем в нормальном человеческом понимании — прямолинейная и буквальная, и что это один из тех редких случаев в программировании, когда название идеально описывает суть. На самом деле, связь почти прямолинейная и почти буквальная, а название описывает суть почти идеально (почему это так — см. ниже), а если быть точным, то совсем не идеально.

### Способы создания словарей

Словари можно создавать разными способами. Например, можно просто указать множество пар:

In [58]:
person = {'name': 'Маша', 'age': 21}
person

{'name': 'Маша', 'age': 21}

Здесь ключом является строка 'name', а его единственным значением — строка 'Маша'. И точно так же, еще одним ключом является строка 'age', а его единственным значением — целое число 21.

Можно использовать функцию `dict`, применив ее к списку кортежей:

In [59]:
coordinates = dict([('x', 10), ('y', 20), ('z', 30)])
coordinates

{'x': 10, 'y': 20, 'z': 30}

Здесь ключи — это строки, а значения ключей — целые числа.

По аналогии со списками, можно использовать генератор словарей:

In [60]:
squares = {x: x**2 for x in range(5)}
squares

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

В этом случае и ключами и значениями являются целые числа.

### Ключи и значения

Доступ к элементам словаря осуществляется по ключу:

In [61]:
person['name']

'Маша'

In [62]:
coordinates['x']

10

При этом ключ должен быть уникальным. В этом — фундаментальное отличие между обычным человеческим пониманием словаря и словарем в смысле структуры данных: есть разница между человеческим языком и строгой логикой машин (см. выше, о семантике понятия «словарь»).

Например, в жизни ключ — это многозначное понятие (гаечный ключ, родник и т. д.), а в информатике — это жесткая привязка. Компьютер не умеет понимать контекст. Если бы ключ мог ссылаться на десять разных значений одновременно, система не знала бы, что именно вернуть при запросе.

Чтобы разрешить этот конфликт, используются две стратегии, которые превращают  многозначность в машинную уникальность:
- массивы значений,
- составные ключи.

Можно передать в качестве значения ключа не единственное значение, а список значений:

In [63]:
d = {
    'ключ': ['инструмент, при помощи которого открывается (закрывается) замок', 
             'бьющий из земли источник воды',
             'секретная информация для расшифровки закодированных данных', 
             'инструмент для закручивания (откручивания) гаек']
}
d['ключ']

['инструмент, при помощи которого открывается (закрывается) замок',
 'бьющий из земли источник воды',
 'секретная информация для расшифровки закодированных данных',
 'инструмент для закручивания (откручивания) гаек']

Или, если нужно разграничить значения, можно сделать ключ более специфичным, используя не слово «ключ», а кортеж слов:

In [64]:
d = {
    ('ключ', 'слесарное дело'): 'инструмент для закручивания (откручивания) гаек',
    ('ключ', 'природоведение'): 'бьющий из земли источник воды',
    ('ключ', 'криптография'): 'секретная информация для расшифровки закодированных данных',
    ('ключ', 'домоводство'): 'инструмент, при помощи которого открывается (закрывается) замок',
}
d[('ключ', 'криптография')]

'секретная информация для расшифровки закодированных данных'

Главное отличие понятия «словарь» в бытовом и компьютерном смыслах — это разница между пониманием и поиском:

- Для человека словарь — это инструмент понимания. Человек может прочитать все варианты и выбрать нужный по контексту.
- Для машины словарь — это инструмент поиска в памяти. Машине не нужно понимать, ей нужно гарантированно вернуть один результат.

### Словари в Data Science

Мы уже использовали словари выше: например, когда указывали `dtype` при чтении файлов cvs. Вообще, следует понимать, что  словарь — это инструмент для преобразования данных и хранения вспомогательной логики (именно она, вспомогательная логика, использовалась при чтении файлов с указанием `dtype`). 

Преобразования можно реализовывать при помощи методa `map`. Например, если нам нужно преобразовать словесное описание рейтинга в числовое, то тогда нужные нам соответствия (вспомогательную логику преобразования) мы описываем именно в виде словаря и после этого выполняем мэппинг:

In [65]:
df

,order_id,customer_id,product,price,rating,quantity,order_date,phone_number,in_stock,discount
0,ORD001,0101,Smartphone,999.99,Top,1,2024-01-15,"(+7, 916, 1234567)",Yes,0.00
1,ORD002,0102,Laptop,1499.99,Medium,1,2024-01-16,"(+7, 916, 1234568)",No,0.00
2,ORD003,0103,Tablet,499.99,Medium,2,2024-01-17,"(+7, 916, 1234569)",Yes,0.15
3,ORD004,0104,Smartphone,999.99,Top,1,2024-01-18,"(+7, 916, 1234570)",Yes,0.00
4,ORD005,0105,Headphones,199.99,Low,3,2024-01-19,"(+7, 916, 1234571)",Yes,0.00
5,ORD006,0106,Laptop,1499.99,Medium,1,2024-01-20,"(+7, 916, 1234572)",No,0.00
6,ORD007,0107,Tablet,499.99,Medium,2,2024-01-21,"(+7, 916, 1234573)",Yes,0.15
7,ORD008,0108,Smartwatch,299.99,Low,1,2024-01-22,"(+7, 916, 1234574)",Yes,0.00
8,ORD009,0109,Headphones,199.99,Low,2,2024-01-23,"(+7, 916, 1234575)",Yes,0.00
9,ORD010,0110,Smartphone,999.99,Top,1,2024-01-24,"(+7, 916, 1234576)",Yes,0.00

In [66]:
rating_map = {'Top': 10, 'Medium': 5, 'Low': 0}

df['rating'] = df['rating'].map(rating_map)
df

,order_id,customer_id,product,price,rating,quantity,order_date,phone_number,in_stock,discount
0,ORD001,0101,Smartphone,999.99,10,1,2024-01-15,"(+7, 916, 1234567)",Yes,0.00
1,ORD002,0102,Laptop,1499.99,5,1,2024-01-16,"(+7, 916, 1234568)",No,0.00
2,ORD003,0103,Tablet,499.99,5,2,2024-01-17,"(+7, 916, 1234569)",Yes,0.15
3,ORD004,0104,Smartphone,999.99,10,1,2024-01-18,"(+7, 916, 1234570)",Yes,0.00
4,ORD005,0105,Headphones,199.99,0,3,2024-01-19,"(+7, 916, 1234571)",Yes,0.00
5,ORD006,0106,Laptop,1499.99,5,1,2024-01-20,"(+7, 916, 1234572)",No,0.00
6,ORD007,0107,Tablet,499.99,5,2,2024-01-21,"(+7, 916, 1234573)",Yes,0.15
7,ORD008,0108,Smartwatch,299.99,0,1,2024-01-22,"(+7, 916, 1234574)",Yes,0.00
8,ORD009,0109,Headphones,199.99,0,2,2024-01-23,"(+7, 916, 1234575)",Yes,0.00
9,ORD010,0110,Smartphone,999.99,10,1,2024-01-24,"(+7, 916, 1234576)",Yes,0.00

Кроме того, есть такой довольно-таки распространённый формат данных — json. При обращении по API многие ресурсы возвращают именно json. Так вот, с точки зрения описания данных, json — это не что иное как вложенный словарь (или список словарей). 

Датафреймы можно сохранять в формате json:

In [67]:
# df.to_json('data/gadget_sales.json')

>#### Задание
Посмотрите на получившийся файл json «изнутри», чтобы увидеть его словарную структуру. Обратите внимание, что и ключи, и значения хранятся в виде строк.

Файлы json, так же как и файлы csv не сохраняют сведения о типах данных. Поэтому, если прочитать файл в датафрейм, то опять могут возникнуть определённые несоответствия (например, ID покупателя опять будет числом):

In [68]:
a = pd.read_json('data/gadget_sales.json')
display(a)
a.info()

,order_id,customer_id,product,price,rating,quantity,order_date,phone_number,in_stock,discount
0,ORD001,101,Smartphone,999.99,10,1,2024-01-15,"[+7, 916, 1234567]",Yes,0.00
1,ORD002,102,Laptop,1499.99,5,1,2024-01-16,"[+7, 916, 1234568]",No,0.00
2,ORD003,103,Tablet,499.99,5,2,2024-01-17,"[+7, 916, 1234569]",Yes,0.15
3,ORD004,104,Smartphone,999.99,10,1,2024-01-18,"[+7, 916, 1234570]",Yes,0.00
4,ORD005,105,Headphones,199.99,0,3,2024-01-19,"[+7, 916, 1234571]",Yes,0.00
5,ORD006,106,Laptop,1499.99,5,1,2024-01-20,"[+7, 916, 1234572]",No,0.00
6,ORD007,107,Tablet,499.99,5,2,2024-01-21,"[+7, 916, 1234573]",Yes,0.15
7,ORD008,108,Smartwatch,299.99,0,1,2024-01-22,"[+7, 916, 1234574]",Yes,0.00
8,ORD009,109,Headphones,199.99,0,2,2024-01-23,"[+7, 916, 1234575]",Yes,0.00
9,ORD010,110,Smartphone,999.99,10,1,2024-01-24,"[+7, 916, 1234576]",Yes,0.00

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      10 non-null     object
 1   customer_id   10 non-null     int64
 2   product       10 non-null     object
 3   price         10 non-null     float64
 4   rating        10 non-null     int64
 5   quantity      10 non-null     int64
 6   order_date    10 non-null     object
 7   phone_number  10 non-null     object
 8   in_stock      10 non-null     object
 9   discount      10 non-null     float64
dtypes: float64(2), int64(3), object(5)
memory usage: 880.0+ bytes

## § 6. Сохраниение типов данных

Формат, ориентированный на сохранение типов данных — это формат parquet. Он создан для эффективного хранения табличных данных с сохранением типов, в отличие от csv, где все — просто текст. Это бинарный формат, то есть, данные в этом формате хранятся не в виде читаемого текста, а в компактном двоичном коде. 

Главная фишка: parquet включают схему данных в заголовок файла. В этой схеме все чётко прописано, например: «столбец age — целое число 64 бита», «столбец name — строка в кодировке UTF-8», «столбец is_active — булевый тип» и т. д. При чтении pandas считывает схему и сразу восстанавливает данные в правильных типах.

Сохраняем данные о продажах гаджетов в формат parquet:

In [69]:
df.to_parquet('data/gadget_sales.parquet')

>#### Задание
Посмотрите на файл parquet «изнутри». Получилось?

Читаем файл parquet:

In [70]:
b = pd.read_parquet('data/gadget_sales.parquet')
b

,order_id,customer_id,product,price,rating,quantity,order_date,phone_number,in_stock,discount
0,ORD001,0101,Smartphone,999.99,10,1,2024-01-15,"[+7, 916, 1234567]",Yes,0.00
1,ORD002,0102,Laptop,1499.99,5,1,2024-01-16,"[+7, 916, 1234568]",No,0.00
2,ORD003,0103,Tablet,499.99,5,2,2024-01-17,"[+7, 916, 1234569]",Yes,0.15
3,ORD004,0104,Smartphone,999.99,10,1,2024-01-18,"[+7, 916, 1234570]",Yes,0.00
4,ORD005,0105,Headphones,199.99,0,3,2024-01-19,"[+7, 916, 1234571]",Yes,0.00
5,ORD006,0106,Laptop,1499.99,5,1,2024-01-20,"[+7, 916, 1234572]",No,0.00
6,ORD007,0107,Tablet,499.99,5,2,2024-01-21,"[+7, 916, 1234573]",Yes,0.15
7,ORD008,0108,Smartwatch,299.99,0,1,2024-01-22,"[+7, 916, 1234574]",Yes,0.00
8,ORD009,0109,Headphones,199.99,0,2,2024-01-23,"[+7, 916, 1234575]",Yes,0.00
9,ORD010,0110,Smartphone,999.99,10,1,2024-01-24,"[+7, 916, 1234576]",Yes,0.00

И (наконец-то!) ID пользователя прочитан как строка.

# Домашнее задание
Вот описание данных о банковских кредитах для оценивания потенциальных заёмщиков:
- id — ID заёмщика (строка),
- age — возраст заёмщика (целое число),
- gender — пол заёмщика (строка),
- income — доход заемщика в 1000 долларов в год (число с плавающей запятой),
- default — вероятность дефолта, основанная на предыдущих кредитах заёмщика (число с плавающей запятой в пределах от 0 до 1),
- amount — сумма кредита (число с плавающей запятой),
- approval — одобрен или не одобрен кредит (логическая переменная),

## Преобразования типов

Если посмотреть на типы данных из файла credit_scoring.csv, то окажется, то не всегда они соответствуют заявленным (ID заёмщика — не строка, возраст — не целое число, одобрение — не логическое выражение). Правда, причины, по которым это происходит не всегда очевидны. Например, возраст в csv — целый, тогда почему после чтения появляется десятичная точка, и он перестаёт быть целым?

>#### Задание
Прочтайте файл credit_scoring.csv из папки data. Преобразуйте ID заёмщика в строковый тип, возраст — в целый, одобрение кредита — в логический. Используйте те приёмы из числа рассмотренных выше, которые вы посчитаете наиболее уместными (или придумайте свои приёмы).

## Форматы 

Ну и чтобы не забывать, что помимо csv существуют и другие форматы для хранения данных.

>#### Задание
> Сохраните преобразованные данные в форматах csv, json и parquet. Заново прочитайте их и сравните типы данных по всем столбцам.

In [ ]:
# Код