# Практика. Типы, структуры и форматы данных

In [1]:
import pandas as pd

Цель занятия — сформировать у студентов навыки критического анализа и первичной предобработки «грязных» данных, научив их выявлять несоответствия фактических типов данных ожидаемым, исправлять ошибки в структурированных наборах через очистку аномальных значений и программную стандартизацию форматов, что является фундаментальным этапом подготовки данных для качественного последующего анализа и построения моделей в Data Science.

>#### Задание 1
Загрузите датасет marketing_campaign из папки data.

In [22]:
df = pd.read_csv('data/marketing_campaign.csv')
df

,user_id,age_group,gender,os_type,session_duration,pages_viewed,discount,conversion
0,1000,36-50,Male,Desktop,506.95,9.0,5,Yes
1,1001,50+,Male,Desktop,275.35,8.0,5,YES
2,1002,18-25,Female,iOS,243.14,12.0,15,No
3,1003,36-50,Female,iOS,556.73,NaN,20,Yes
4,1004,36-50,Female,Desktop,439.09,33.0,10,No
5,1005,50+,Male,Android,202.66,48.0,15%,Yes
6,1006,18-25,Female,iOS,346.56,23.0,15,No
7,1007,18-25,Male,Android,317.29,24.0,20,No
8,1008,36-50,Male,Android,577.09,37.0,15,Yes
9,1009,26-35,M,Android,508.27,35.0,20,No
10,1010,36-50,Male,iOS,450.92,44.0,ten,No
11,1011,36-50,Male,Android,328.42,40.0,10,No
12,1012,36-50,Female,iOS,356.18,NaN,20,Yes
13,1013,36-50,Female,Android,579.50,27.0,15,Yes
14,1014,25-30,Female,Desktop,368.15,35.0,20,Yes
15,1015,18-25,Female,Desktop,172.84,1.0,10,Yes
16,1016,50+,Female,iOS,184.80,35.0,10,No
17,1017,50+,Male,Desktop,107.51,37.0,15,No
18,1018,50+,Female,Desktop,19.23,47.0,15%,Yes
19,1019,36-50,Female,Android,259.81,14.0,5,1
20,1020,26-35,Male,iOS,242.98,3.0,20,Yes
21,1021,18-25,Female,Android,183.16,1.0,0,No
22,1022,26-35,Male,Android,18.31,5.0,NaN,No
23,1023,50+,Female,Android,127.32,26.0,15,Yes
24,1024,50+,Male,Android,429.69,14.0,15,No
25,1025,26-35,Female,Android,476.20,NaN,15,Yes
26,1026,26-35,Female,Android,367.52,27.0,15,No
27,1027,26-35,Male,Android,556.52,9.0,15,0
28,1028,50+,Male,iOS,394.14,15.0,10,Yes
29,1029,50+,Male,Desktop,549.83,15.0,5,No

Датасет содержит сведения о реакции пользователей на запущенную рекламную кампанию. Структура датасета такова:
- user_id — ID пользователя (строка),
- age_group — возрастная группа (строка),
- gender — пол (строка),
- os_type — операционная система (строка),
- session_duration — длительность сессии на сайте в секундах (число с плавающей запятой),
- pages_viewed —  число просмотренных страниц (целое число),
- discount — предложенная скидка в % (целое число),
- conversion — конверсия, совершил ли пользователь полезное действие (логический тип).

>#### Задание 2
>Просмотрите информацию о данных при помощи метода `info()`. Что не так?

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           30 non-null     int64
 1   age_group         30 non-null     object
 2   gender            30 non-null     object
 3   os_type           30 non-null     object
 4   session_duration  30 non-null     float64
 5   pages_viewed      27 non-null     float64
 6   discount          29 non-null     object
 7   conversion        30 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 2.0+ KB

## Преобразования типов

>#### Задание 3
При загрузке данных укажите правильные типы для столбцов:
>- user_id должен быть строкой
>- discount должен быть целым числом
>- conversion должен быть логическим выражением.
>
>Почему возникают ошибки? Загрузите хотя бы ID пользователя как строки. С остальными столбцами придется разбираться по-другому.

In [5]:
df = pd.read_csv('data/marketing_campaign.csv', dtype = {'user_id':str, 'discount':int, 'conversion':bool})
df.head(3)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           30 non-null     object
 1   age_group         30 non-null     object
 2   gender            30 non-null     object
 3   os_type           30 non-null     object
 4   session_duration  30 non-null     float64
 5   pages_viewed      27 non-null     float64
 6   discount          29 non-null     object
 7   conversion        30 non-null     object
dtypes: float64(2), object(6)
memory usage: 2.0+ KB

>#### Задание 4
Столбец pages_viewed должен быть целым числом, но читается как число с плавающей запятой. Найдите все пропущенные значения в этом столбце, заполните их медианным значением при помощи метода `fillna` и преобразуйте столбец к целому типу при помощи метода `astype`.

In [6]:
df['pages_viewed'] = df['pages_viewed'].fillna(df['pages_viewed'].median()).astype(int)
display(df.head(3))
df.info()

,user_id,age_group,gender,os_type,session_duration,pages_viewed,discount,conversion
0,1000,36-50,Male,Desktop,506.95,9,5,Yes
1,1001,50+,Male,Desktop,275.35,8,5,YES
2,1002,18-25,Female,iOS,243.14,12,15,No

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           30 non-null     object
 1   age_group         30 non-null     object
 2   gender            30 non-null     object
 3   os_type           30 non-null     object
 4   session_duration  30 non-null     float64
 5   pages_viewed      30 non-null     int32
 6   discount          29 non-null     object
 7   conversion        30 non-null     object
dtypes: float64(1), int32(1), object(6)
memory usage: 1.9+ KB

>#### Задание 5
Используя мэппинг, замените все значения в столбце conversion на корректные строки 'Yes' и 'No'. Затем при помощи генератора списков преобразуйте этот столбец в стобец с логическими значениями.

In [7]:
df['conversion'].unique()

array(['Yes', 'YES', 'No', '1', '0'], dtype=object)

In [8]:
conversion_map = {'Yes':True, 'YES':True, 'No':False, '1':True, '0':False}
df['conversion'] = df['conversion'].map(conversion_map)

In [8]:
display(df.head(10))
df.info()

,user_id,age_group,gender,os_type,session_duration,pages_viewed,discount,conversion
0,1000,36-50,Male,Desktop,506.95,9,5,True
1,1001,50+,Male,Desktop,275.35,8,5,True
2,1002,18-25,Female,iOS,243.14,12,15,False
3,1003,36-50,Female,iOS,556.73,24,20,True
4,1004,36-50,Female,Desktop,439.09,33,10,False
5,1005,50+,Male,Android,202.66,48,15%,True
6,1006,18-25,Female,iOS,346.56,23,15,False
7,1007,18-25,Male,Android,317.29,24,20,False
8,1008,36-50,Male,Android,577.09,37,15,True
9,1009,26-35,M,Android,508.27,35,20,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           30 non-null     object
 1   age_group         30 non-null     object
 2   gender            30 non-null     object
 3   os_type           30 non-null     object
 4   session_duration  30 non-null     float64
 5   pages_viewed      30 non-null     int32
 6   discount          29 non-null     object
 7   conversion        30 non-null     bool
dtypes: bool(1), float64(1), int32(1), object(5)
memory usage: 1.7+ KB

>#### Задание 6
Аналогично предыдущему заданию, замените некорректные значения в столбце discount и преобразуйте его к целому типу (пропущенное значение замените на 0).

In [9]:
df['discount'].unique()

array(['5', '15', '20', '10', '15%', 'ten', '0', nan], dtype=object)

In [10]:
df['discount'] = df['discount'].fillna(0)
df['discount'].unique()

array(['5', '15', '20', '10', '15%', 'ten', '0', 0], dtype=object)

In [11]:
discount_map = {0:0, '0':0, '5':5, '10':10, '15':15, '20':20, '15%':15, 'ten':10}
df['discount'] = df['discount'].map(discount_map)
df['discount'].unique()

array([ 5, 15, 20, 10,  0], dtype=int64)

>#### Задание 7
Аналогично предыдущему заданию замените некорректные выражения в столбцах gender и age_group. Подсказка: для поиска некорректной возрастной группы воспользуйтесь подсчетом частот при помощи метода `value_counts`.

In [12]:
df['gender'].unique()

array(['Male', 'Female', 'M'], dtype=object)

In [13]:
gender_map = {'Male':'Male', 'Female':'Female', 'M':'Male'}
df['gender'] = df['gender'].map(gender_map)
df['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [14]:
df['age_group'].value_counts()

36-50    9
50+      9
26-35    6
18-25    5
25-30    1
Name: age_group, dtype: int64

In [15]:
age_group_map = {'18-25':'18-25', '26-35':'26-35', '36-50':'36-50', '50+':'50+', '25-30':'26-35'}
df['age_group'] = df['age_group'].map(age_group_map)
df['age_group'].unique()

array(['36-50', '50+', '18-25', '26-35'], dtype=object)

In [16]:
display(df)
df.info()

,user_id,age_group,gender,os_type,session_duration,pages_viewed,discount,conversion
0,1000,36-50,Male,Desktop,506.95,9,5,True
1,1001,50+,Male,Desktop,275.35,8,5,True
2,1002,18-25,Female,iOS,243.14,12,15,False
3,1003,36-50,Female,iOS,556.73,24,20,True
4,1004,36-50,Female,Desktop,439.09,33,10,False
5,1005,50+,Male,Android,202.66,48,15,True
6,1006,18-25,Female,iOS,346.56,23,15,False
7,1007,18-25,Male,Android,317.29,24,20,False
8,1008,36-50,Male,Android,577.09,37,15,True
9,1009,26-35,Male,Android,508.27,35,20,False
10,1010,36-50,Male,iOS,450.92,44,10,False
11,1011,36-50,Male,Android,328.42,40,10,False
12,1012,36-50,Female,iOS,356.18,24,20,True
13,1013,36-50,Female,Android,579.50,27,15,True
14,1014,26-35,Female,Desktop,368.15,35,20,True
15,1015,18-25,Female,Desktop,172.84,1,10,True
16,1016,50+,Female,iOS,184.80,35,10,False
17,1017,50+,Male,Desktop,107.51,37,15,False
18,1018,50+,Female,Desktop,19.23,47,15,True
19,1019,36-50,Female,Android,259.81,14,5,True
20,1020,26-35,Male,iOS,242.98,3,20,True
21,1021,18-25,Female,Android,183.16,1,0,False
22,1022,26-35,Male,Android,18.31,5,0,False
23,1023,50+,Female,Android,127.32,26,15,True
24,1024,50+,Male,Android,429.69,14,15,False
25,1025,26-35,Female,Android,476.20,24,15,True
26,1026,26-35,Female,Android,367.52,27,15,False
27,1027,26-35,Male,Android,556.52,9,15,False
28,1028,50+,Male,iOS,394.14,15,10,True
29,1029,50+,Male,Desktop,549.83,15,5,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           30 non-null     object
 1   age_group         30 non-null     object
 2   gender            30 non-null     object
 3   os_type           30 non-null     object
 4   session_duration  30 non-null     float64
 5   pages_viewed      30 non-null     int32
 6   discount          30 non-null     int64
 7   conversion        30 non-null     bool
dtypes: bool(1), float64(1), int32(1), int64(1), object(4)
memory usage: 1.7+ KB

>#### Задание 8
Задание
Сохраните датафрейм в файлы marketing_campaign_new (с обязательным добавлением new, чтобы не искажать исходный «грязный» файл) в форматах csv и parquet. Прочитайте эти файлы. При чтении файла csv используйте атрибут `dtype`.

In [17]:
# df.to_csv('data/marketing_campaign_new.csv', index = False)
# df.to_parquet('data/marketing_campaign_new.parquet')

In [17]:
a = pd.read_csv('data/marketing_campaign_new.csv', dtype={'user_id':str})
display(a.head(3))
a.info()

,user_id,age_group,gender,os_type,session_duration,pages_viewed,discount,conversion
0,1000,36-50,Male,Desktop,506.95,9,5,True
1,1001,50+,Male,Desktop,275.35,8,5,True
2,1002,18-25,Female,iOS,243.14,12,15,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           30 non-null     object
 1   age_group         30 non-null     object
 2   gender            30 non-null     object
 3   os_type           30 non-null     object
 4   session_duration  30 non-null     float64
 5   pages_viewed      30 non-null     int64
 6   discount          30 non-null     int64
 7   conversion        30 non-null     bool
dtypes: bool(1), float64(1), int64(2), object(4)
memory usage: 1.8+ KB

In [18]:
b = pd.read_parquet('data/marketing_campaign_new.parquet')
display(b.head(3))
b.info()

,user_id,age_group,gender,os_type,session_duration,pages_viewed,discount,conversion
0,1000,36-50,Male,Desktop,506.95,9,5,True
1,1001,50+,Male,Desktop,275.35,8,5,True
2,1002,18-25,Female,iOS,243.14,12,15,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           30 non-null     object
 1   age_group         30 non-null     object
 2   gender            30 non-null     object
 3   os_type           30 non-null     object
 4   session_duration  30 non-null     float64
 5   pages_viewed      30 non-null     int32
 6   discount          30 non-null     int64
 7   conversion        30 non-null     bool
dtypes: bool(1), float64(1), int32(1), int64(1), object(4)
memory usage: 1.7+ KB

## Генерация признаков

>#### Задание 9
При помощи генератора списков создайте новый бинарный признак логического типа is_mobile (мобильный пользователь) по принципу: если пользователь использует десктопное приложение, он не мобилен.

In [19]:
df = pd.read_parquet('data/marketing_campaign_new.parquet')
display(df.head(3))
df.info()

,user_id,age_group,gender,os_type,session_duration,pages_viewed,discount,conversion
0,1000,36-50,Male,Desktop,506.95,9,5,True
1,1001,50+,Male,Desktop,275.35,8,5,True
2,1002,18-25,Female,iOS,243.14,12,15,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           30 non-null     object
 1   age_group         30 non-null     object
 2   gender            30 non-null     object
 3   os_type           30 non-null     object
 4   session_duration  30 non-null     float64
 5   pages_viewed      30 non-null     int32
 6   discount          30 non-null     int64
 7   conversion        30 non-null     bool
dtypes: bool(1), float64(1), int32(1), int64(1), object(4)
memory usage: 1.7+ KB

In [20]:
df['is_mobile'] = [False if x == 'Desktop' else True for x in df['os_type']]
display(df.head(3))
df.info()

,user_id,age_group,gender,os_type,session_duration,pages_viewed,discount,conversion,is_mobile
0,1000,36-50,Male,Desktop,506.95,9,5,True,False
1,1001,50+,Male,Desktop,275.35,8,5,True,False
2,1002,18-25,Female,iOS,243.14,12,15,False,True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           30 non-null     object
 1   age_group         30 non-null     object
 2   gender            30 non-null     object
 3   os_type           30 non-null     object
 4   session_duration  30 non-null     float64
 5   pages_viewed      30 non-null     int32
 6   discount          30 non-null     int64
 7   conversion        30 non-null     bool
 8   is_mobile         30 non-null     bool
dtypes: bool(2), float64(1), int32(1), int64(1), object(4)
memory usage: 1.7+ KB

>#### Задание 10
При помощи мэппинга создайте новый числовой признак age_activity, описывающий среднее время сессии для каждой возрастной группы.

In [21]:
age_activity_map = {'18-25':round(df.loc[df['age_group'] == '18-25']['session_duration'].mean(), 2),
                    '26-35':round(df.loc[df['age_group'] == '26-35']['session_duration'].mean(), 2),
                    '36-50':round(df.loc[df['age_group'] == '36-50']['session_duration'].mean(), 2),
                    '50+'  :round(df.loc[df['age_group'] == '50+'  ]['session_duration'].mean(), 2)}
df['age_activity'] = df['age_group'].map(age_activity_map)
display(df.head(3))
df.info()

,user_id,age_group,gender,os_type,session_duration,pages_viewed,discount,conversion,is_mobile,age_activity
0,1000,36-50,Male,Desktop,506.95,9,5,True,False,450.52
1,1001,50+,Male,Desktop,275.35,8,5,True,False,254.50
2,1002,18-25,Female,iOS,243.14,12,15,False,True,252.60

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           30 non-null     object
 1   age_group         30 non-null     object
 2   gender            30 non-null     object
 3   os_type           30 non-null     object
 4   session_duration  30 non-null     float64
 5   pages_viewed      30 non-null     int32
 6   discount          30 non-null     int64
 7   conversion        30 non-null     bool
 8   is_mobile         30 non-null     bool
 9   age_activity      30 non-null     float64
dtypes: bool(2), float64(2), int32(1), int64(1), object(4)
memory usage: 1.9+ KB

# Домашнее задание

>#### Задание
Прочитайте файл churn.csv из папки data.

Это данные телеком-оператора с различными сведениями о клиентах, в том числе — со сведениями об их оттоке (часть клиентов уходит к другим операторам). Структура датасета такова:
- customer_id — ID клиента (строка),
- lifetime — «cрок жизни» клиента в месяцах (целое число),
- contract_type — тип контракта, возможные значения: 'month', 'half year', 'year' (строка),
- monthly_charges — ежемесячный платёж (числа с плавающей запятой),
- tech_support — подключена ли техническая поддержка (логический тип),
- satisfaction — оценка удовлетворенности от 0 до 10 (целое число),
- churn — отток абонентов: ушел ли клиент (логический тип).

>#### Задание
>1) Просмотрите информацию о датасете при помощи метода `info`. Все ли в порядке?
>1) Преобразуйте ID пользователя в строковый тип при помощи метода astype.
>2) Столбец lifetime должен быть целочисленным, но читается как числа с плавающей запятой. Найдите пропущенные значения, замените их на медианные и переведите этот столбец в целый формат.
>3) Столбец contract_type должен содержать три значения: 'month', 'half year', 'year'. Выясните, нет ли в этом столбце пропусков, и, если они есть, замените их на наиболее частотную строку.
>1) При помощи метода `unique` выясните, какие значения есть в столбце tech_support. Затем при помощи мэппинга переведите столбец в логический тип.
>1) Аналогично столбец satisfaction переведите в целый тип.
>1) Аналогично столбец churn переведите в логический тип.
>1) Создайте новый признак churn_by_contract, приписав каждому из трёх типов контракта среднюю долю лояльных клиентов.
>1) Сохраните датафрейм в форматах csv и parquet. Прочитайте их заново, при необходимости (для файла csv) указав нужные типы данных.